server:
  port: 8081

spring:
  # 微服务配置
  application:
    name: api-passenger
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # 注册中心地址

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379

