server:
  port: 8086

spring:
  # 微服务配置
  application:
    name: service-driver-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service_driver_user?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
