<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fc</groupId>
        <artifactId>online-taxi-public</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>base-service</artifactId>
    <packaging>pom</packaging>

    <modules>
        <!-- 乘客用户api -->
        <module>api-passenger</module>

        <!-- 验证码服务 -->
        <module>service-verification</module>

        <!-- 乘客服务 -->
        <module>service-passenger-user</module>

        <!-- 价格服务 -->
        <module>service-price</module>

        <!-- 地图服务 -->
        <module>service-map</module>

        <!-- 司机用户服务 -->
        <module>service-driver-user</module>

        <!-- BOSS -->
        <module>api-boss</module>

        <!-- 司机用户api -->
        <module>api-driver</module>

    </modules>

    <dependencies>

<!--        Web 应用-->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- 注册中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <!-- 配置中心 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <!-- openfeign，服务间调用 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>

        <!-- 负载均衡 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>

        <!-- 自定义公共工具包 -->
        <dependency>
            <groupId>com.fc</groupId>
            <artifactId>internal-common</artifactId>
            <!-- 修正：添加版本号，使用项目统一版本 -->
            <version>${project.version}</version>
        </dependency>

        <!-- JSON工具 -->
        <dependency>
            <groupId>net.sf.json-lib</groupId>
            <artifactId>json-lib</artifactId>
            <classifier>jdk15</classifier>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

    </dependencies>

    <!-- 所有业务服务自动继承Spring Boot打包插件 -->
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>